apiVersion: v1
kind: Service
metadata:
  name: mocktest-frontend
  namespace: applications
spec:
  selector:
    app: mocktest-frontend
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 3000
  type: ClusterIP
