apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 5m0s
  chart:
    spec:
      chart: prometheus
      version: 25.26.0
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: monitoring
  values:
    server:
      service:
        type: ClusterIP
      persistentVolume:
        enabled: false
    alertmanager:
      enabled: false
