apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-app
  template:
    metadata:
      labels:
        app: library-app
    spec:
      containers:
        - name: library-app
          image: harsha3330/library-management-system:dev-24-date-20240827-111629
          ports:
            - containerPort: 3000
          env:
            - name: AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: library-app-secret
                  key: AUTH_SECRET
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: library-app-secret
                  key: DATABASE_URL
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: library-app-secret
                  key: AWS_REGION
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: library-app-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: library-app-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_S3_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: library-app-secret
                  key: AWS_S3_BUCKET_NAME
