FROM node:20.16-slim
WORKDIR /app
COPY library-management-system/package*.json /app/
RUN npm install
RUN apt-get update -y && apt-get install -y openssl
COPY library-management-system /app
EXPOSE 3000
CMD ["sh", "-c", "npx prisma generate --schema=./prisma/schema.prisma && npm run dev"]
