apiVersion: v1
kind: Service
metadata:
  name: library-app
  namespace: applications
spec:
  selector:
    app: library-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
