apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mocktest-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Harsha190202/EKS.git
    targetRevision: main
    path: k8-manifests/mocktest-frontend
  destination:
    server: "https://kubernetes.default.svc"
    namespace: applications
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
